### ISSUE TITLE
address vs direct access

### ISSUE THREAD

**Issue by y-top-developer** [PatrickAlphaC/storage_factory#10]
https://github.com/PatrickAlphaC/storage_factory/blob/29f26ee7c24706ea13989fe9f1f81963d1a3f9f5/StorageFactory.sol#L28

Hi!

Why do you use: `getting object by address` -> `getting address` -> `getting object by index` instead of just `getting object by index`?
like: `return simpleStorageArray[_simpleStorageIndex].retrieve();`

**Comment by PatrickAlphaC** [comment]
It was meant to be a way to teach what's going on... but yes a few others also told me this was actually more confusing for them. Thanks for pointing it out!
