### ISSUE TITLE
Execute SimpleStorage functions in StorageFactory contract

### ISSUE THREAD

**Issue by pieringro** [PatrickAlphaC/storage_factory#3]
HI Patrick, thank you for your lessons.
In StorageFactory.sol, what is the difference between
`SimpleStorage(address(simpleStorageArray[_simpleStorageIndex])).store(_simpleStorageNumber)`
and
`SimpleStorage simpleStorage = simpleStorageArray[_simpleStorageIndex];`
`simpleStorage.store(_simpleStorageFavoriteNumber);`

Anyway, your lessons are very useful, I love your way of explaining

EDIT: maybe differences between versions? I'm using pragma solidity ^0.8.0

**Comment by PatrickAlphaC** [comment]
They are the same :)
