### ISSUE TITLE
brownie compile wont work 

### ISSUE THREAD

**Issue by TosiroNakamoto** [PatrickAlphaC/storage_factory#9]
if i run `brownie compile` i get 
INFO: Could not find files for the given pattern(s).
Brownie v1.19.0 - Python development framework for Ethereum

Project has been compiled. Build artifacts saved at C:\Users\User\OneDrive\Documenten\demo\build\contracts

but its not in there

**Comment by PatrickAlphaC** [comment]
"but its not in there" what does that mean?

**Comment by TosiroNakamoto** [comment]
the compiled file should be in the contracts folder but its not there and its no where else so it just didn't 
compile

**Comment by PatrickAlphaC** [comment]
I'm going to close for now, this repo isn't using brownie. Hard to help here if you're doing your own thing here.
